from django.contrib import admin
from api.models import *


admin.site.register(Category)
admin.site.register(Commodity)
admin.site.register(Economy)
admin.site.register(Faction)
admin.site.register(Government)
admin.site.register(Allegiance)
admin.site.register(State)
admin.site.register(Security)
admin.site.register(System)
admin.site.register(StationType)
admin.site.register(Station)
admin.site.register(Listing)
admin.site.register(AllegianceRank)
admin.site.register(ModuleType)
admin.site.register(ModuleParameterType)
admin.site.register(ModuleParameter)
admin.site.register(Module)
admin.site.register(ShipSlot)
admin.site.register(ShipParameterType)
admin.site.register(ShipParameter)
admin.site.register(ShipType)
admin.site.register(Ship)
